version: "3.9"
services:
  postgres:
    image: postgres:14.0
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"